#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026-present ROCKNIX (https://github.com/ROCKNIX)
# Modified by Radical <radical@radical.fun>

STEAM="${HOME}/.local/share/Steam"
STEAM_DOT="${HOME}/.steam"
RUNTIME_DIR="${STEAM}/steam-runtime-steamrt-arm64"
CLIENT_DIR="${STEAM}/steamrtarm64"
PROTON_NAME="Proton 11.0 (ARM64)"
PROTON_DIR="${STEAM}/steamapps/common/${PROTON_NAME}"
RUNTIME_TAR_URL="https://repo.steampowered.com/steamrt3c/images/latest-public-beta/steam-runtime-steamrt-arm64.tar.xz"
STEAM_MANIFEST_URL="https://client-update.fastly.steamstatic.com/steam_client_publicbeta_linuxarm64"
STEAM_CDN="https://client-update.steamstatic.com"

# --- Logging & Error Handling Helpers ---
log_info() { echo -e "[\033[1;34mINFO\033[0m] $1"; }
log_success() { echo -e "[\033[1;32mSUCCESS\033[0m] $1"; sleep 10; exit 0; }
die() { echo -e "[\033[1;31mERROR\033[0m] $1" >&2; sleep 10; exit 1; }
# ----------------------------------------

install_steam_runtime_arm64() {
  if [ -d "${RUNTIME_DIR}" ]; then
    log_info "Steam runtime already exists. Skipping."
    return 0
  fi
  log_info "Downloading and installing Steam runtime (ARM64)..."
  local tar_path="${STEAM}/steam-runtime-steamrt-arm64.tar.xz"

  wget -c -t 5 -O "${tar_path}" "${RUNTIME_TAR_URL}" || die "Failed to download Steam runtime."
  tar xvf "${tar_path}" -C "${STEAM}" || die "Failed to extract Steam runtime."
  rm -f "${tar_path}"
}

symlink_libraries() {
  mkdir -p "${STEAM}/lib/aarch64-linux-gnu"

  local target
  target=$(echo "${STEAM}"/steam-runtime-steamrt-arm64/steamrt3c_platform_*/files/lib/aarch64-linux-gnu/libibus-1.0.so.5.* | head -n 1)
  symlink="${STEAM}/lib/aarch64-linux-gnu/libibus-1.0.so.5"
  if [ ! -f "$target" ]; then
      die "Could not locate libibus target inside runtime."
  fi

  if [[ ! -L "$symlink" ]] || [[ ! -e "$symlink" ]]; then
    ln -sf "${target}" "${symlink}" || die "Failed to symlink libibus."
    loginfo "libibus-1.0.so.5 created/updated"
  fi

  local target
  local symlink
  target=$(echo "${STEAM}"/steam-runtime-steamrt-arm64/steamrt3c_platform_*/files/lib/aarch64-linux-gnu/libgtk-x11-2.0.so.0.* | head -n 1)
  symlink="${STEAM}/lib/aarch64-linux-gnu/libgtk-x11-2.0.so.0"
  if [ ! -f "$target" ]; then
      die "Could not locate libibus target inside runtime."
  fi

  if [[ ! -L "$symlink" ]] || [[ ! -e "$symlink" ]]; then
    ln -sf "${target}" "${symlink}" || die "Failed to symlink libgtk-x11."
    log_info "libgtk-x11-2.0.so.0 symlink created"
  fi

  local target
  local symlink
  target=$(echo "${STEAM}"/steam-runtime-steamrt-arm64/steamrt3c_platform_*/files/lib/aarch64-linux-gnu/libgdk-x11-2.0.so.0.* | head -n 1)
  symlink="${STEAM}/lib/aarch64-linux-gnu/libgdk-x11-2.0.so.0"
  if [ ! -f "$target" ]; then
      die "Could not locate libibus target inside runtime."
  fi

  if [[ ! -L "$symlink" ]] || [[ ! -e "$symlink" ]]; then
    ln -sf "${target}" "${symlink}" || die "Failed to symlink libgdk-x11."
    log_info "libgdk-x11-2.0.so.0 symlink created"
  fi

  local target
  local symlink
  target="$(find /usr/lib64 -maxdepth 1 -name 'libvpx.so.*' -type f | head -1)"
  symlink="${STEAM}/lib/aarch64-linux-gnu/libvpx.so.6"
  if [ ! -f "$target" ]; then
      die "Could not locate libibus target inside runtime."
  fi

  if [[ ! -L "${symlink}" ]] || [[ ! -e "${symlink}" ]]; then
    ln -sf "${target}" "${symlink}" || die "Failed to symlink libvpx."
    log_info "libgdk-x11-2.0.so.0 symlink created"
  fi
}

install_steam_client_arm64() {
  if [ -d "${CLIENT_DIR}" ]; then
    log_info "Steam client already exists. Skipping."
    return 0
  fi
  log_info "Downloading and installing Steam client (ARM64)..."
  local manifest target_file zip_path

  manifest=$(curl -fsSL "${STEAM_MANIFEST_URL}" | strings) || die "Failed to fetch Steam manifest."
  target_file=$(echo "${manifest}" | grep -oP 'bins_linuxarm64_linuxarm64\.zip\.(?!vz\.)[^"]+') || die "Failed to parse target file from manifest."
  zip_path="${STEAM}/linuxarm64.zip"

  wget -c -t 5 -O "${zip_path}" "${STEAM_CDN}/${target_file}" || die "Failed to download Steam client zip."
  unzip -o "${zip_path}" -d "${STEAM}" || die "Failed to extract Steam client."
  rm -f "${zip_path}"

  chmod +x "${CLIENT_DIR}/steam" || die "Failed to make Steam client executable."

  mkdir -p "${STEAM}/package"
  echo publicbeta > "${STEAM}/package/beta"
  mkdir -p "${STEAM_DOT}"
  ln -sfn "${STEAM}" "${STEAM_DOT}/steam" || die "Failed to symlink ${STEAM_DOT}/.steam/steam."
  ln -sfn "${STEAM}/linuxarm64" "${STEAM_DOT}/sdkarm64" || die "Failed to symlink ${STEAM_DOT}/sdkarm64."

  mkdir -p "${STEAM}/compatibilitytools.d/"
  if [ -d "${STEAM}/compatibilitytools.d/Proton11ARM" ]; then
    log_info "Proton already symlinked. Skipping."
  else
    ln -sfn "${PROTON_DIR}/" "${STEAM}/compatibilitytools.d/Proton11ARM" || die "Failed to symlink Proton11ARM."
  fi
  cp -f "/usr/share/steam/compatibilitytool.vdf" "${STEAM}/compatibilitytools.d/" || die "Failed to copy compatibilitytool.vdf."
}

install_bundled_proton_files() {
  log_info "Installing bundled Proton files..."
  mkdir -p "${STEAM_DOT}" "${PROTON_DIR}/"
  cp -f "/usr/share/steam/toolmanifest.vdf" "${PROTON_DIR}/" || die "Failed to copy toolmanifest.vdf."
  cp -f "/usr/share/steam/registry.vdf" "${STEAM_DOT}" || die "Failed to copy registry.vdf."
}

# --- Execution ---
log_info "Starting Steam Installation Process..."

install_steam_runtime_arm64
symlink_libraries
install_steam_client_arm64
install_bundled_proton_files

echo ""
log_info "Starting Steam with arguments $@"
LD_LIBRARY_PATH=${HOME}/.local/share/Steam/lib/aarch64-linux-gnu/:${LD_LIBRARY_PATH} $HOME/.local/share/Steam/steamrtarm64/steam "$@"

